version: '3'

volumes:
  mysql:
  redis:

networks:
  simple-admin:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16

services:
  mysql:
    image: mysql:8.0.21
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'simple_admin'
      MYSQL_ROOT_PASSWORD: 'simple-admin.'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      simple-admin:
        aliases:
          - mysqlserver
        ipv4_address: 10.5.0.2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.05'
          memory: 200M

  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      simple-admin:
        aliases:
          - redisserver
        ipv4_address: 10.5.0.3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M
  core-rpc:
    image: ryanpower/core-rpc:0.2.4
    container_name: core-rpc
    restart: always
    ports:
      - '9101:9101'
    networks:
      simple-admin:
        aliases:
          - core-rpc
        ipv4_address: 10.5.0.4
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  core-api:
    image: ryanpower/core-api:0.2.4
    container_name: core-api
    restart: always
    ports:
      - '9100:9100'
    networks:
      simple-admin:
        aliases:
          - core-api
        ipv4_address: 10.5.0.5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M

  backend-ui:
    image: ryanpower/backend-ui-demo:0.2.0
    container_name: backend-ui
    restart: always
    ports:
      - '80:80'
    networks:
      simple-admin:
        aliases:
          - backend-ui
        ipv4_address: 10.5.0.6
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.05'
          memory: 200M