// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/huuhoait/zero-admin-core/rpc/ent/merchantmeta"
	"github.com/huuhoait/zero-admin-core/rpc/ent/predicate"
)

// MerchantMetaDelete is the builder for deleting a MerchantMeta entity.
type MerchantMetaDelete struct {
	config
	hooks    []Hook
	mutation *MerchantMetaMutation
}

// Where appends a list predicates to the MerchantMetaDelete builder.
func (mmd *MerchantMetaDelete) Where(ps ...predicate.MerchantMeta) *MerchantMetaDelete {
	mmd.mutation.Where(ps...)
	return mmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mmd *MerchantMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, MerchantMetaMutation](ctx, mmd.sqlExec, mmd.mutation, mmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mmd *MerchantMetaDelete) ExecX(ctx context.Context) int {
	n, err := mmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mmd *MerchantMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(merchantmeta.Table, sqlgraph.NewFieldSpec(merchantmeta.FieldID, field.TypeUint64))
	if ps := mmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mmd.mutation.done = true
	return affected, err
}

// MerchantMetaDeleteOne is the builder for deleting a single MerchantMeta entity.
type MerchantMetaDeleteOne struct {
	mmd *MerchantMetaDelete
}

// Where appends a list predicates to the MerchantMetaDelete builder.
func (mmdo *MerchantMetaDeleteOne) Where(ps ...predicate.MerchantMeta) *MerchantMetaDeleteOne {
	mmdo.mmd.mutation.Where(ps...)
	return mmdo
}

// Exec executes the deletion query.
func (mmdo *MerchantMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := mmdo.mmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{merchantmeta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mmdo *MerchantMetaDeleteOne) ExecX(ctx context.Context) {
	if err := mmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
