// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyCreatedBy(value string) *APIUpdate {
	if value != "" {
		return a.SetCreatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyCreatedBy(value string) *APIUpdateOne {
	if value != "" {
		return a.SetCreatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyUpdatedBy(value string) *APIUpdate {
	if value != "" {
		return a.SetUpdatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyUpdatedBy(value string) *APIUpdateOne {
	if value != "" {
		return a.SetUpdatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyPath(value string) *APIUpdate {
	if value != "" {
		return a.SetPath(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyPath(value string) *APIUpdateOne {
	if value != "" {
		return a.SetPath(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyDescription(value string) *APIUpdate {
	if value != "" {
		return a.SetDescription(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyDescription(value string) *APIUpdateOne {
	if value != "" {
		return a.SetDescription(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyAPIGroup(value string) *APIUpdate {
	if value != "" {
		return a.SetAPIGroup(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyAPIGroup(value string) *APIUpdateOne {
	if value != "" {
		return a.SetAPIGroup(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdate) SetNotEmptyMethod(value string) *APIUpdate {
	if value != "" {
		return a.SetMethod(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *APIUpdateOne) SetNotEmptyMethod(value string) *APIUpdateOne {
	if value != "" {
		return a.SetMethod(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdate) SetNotEmptyCreatedBy(value string) *AuditUpdate {
	if value != "" {
		return a.SetCreatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdateOne) SetNotEmptyCreatedBy(value string) *AuditUpdateOne {
	if value != "" {
		return a.SetCreatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdate) SetNotEmptyUpdatedBy(value string) *AuditUpdate {
	if value != "" {
		return a.SetUpdatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdateOne) SetNotEmptyUpdatedBy(value string) *AuditUpdateOne {
	if value != "" {
		return a.SetUpdatedBy(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdate) SetNotEmptyObjectName(value string) *AuditUpdate {
	if value != "" {
		return a.SetObjectName(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdateOne) SetNotEmptyObjectName(value string) *AuditUpdateOne {
	if value != "" {
		return a.SetObjectName(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdate) SetNotEmptyActionName(value string) *AuditUpdate {
	if value != "" {
		return a.SetActionName(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdateOne) SetNotEmptyActionName(value string) *AuditUpdateOne {
	if value != "" {
		return a.SetActionName(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdate) SetNotEmptyChangedData(value string) *AuditUpdate {
	if value != "" {
		return a.SetChangedData(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (a *AuditUpdateOne) SetNotEmptyChangedData(value string) *AuditUpdateOne {
	if value != "" {
		return a.SetChangedData(value)
	}
	return a
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyCreatedBy(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetCreatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyCreatedBy(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetCreatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyUpdatedBy(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetUpdatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyUpdatedBy(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetUpdatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyStatus(value uint8) *DepartmentUpdate {
	if value != 0 {
		return d.SetStatus(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyStatus(value uint8) *DepartmentUpdateOne {
	if value != 0 {
		return d.SetStatus(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptySort(value uint32) *DepartmentUpdate {
	if value != 0 {
		return d.SetSort(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptySort(value uint32) *DepartmentUpdateOne {
	if value != 0 {
		return d.SetSort(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyName(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetName(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyName(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetName(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyAncestors(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetAncestors(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyAncestors(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetAncestors(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyLeader(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetLeader(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyLeader(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetLeader(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyPhone(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetPhone(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyPhone(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetPhone(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyEmail(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetEmail(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyEmail(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetEmail(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyRemark(value string) *DepartmentUpdate {
	if value != "" {
		return d.SetRemark(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyRemark(value string) *DepartmentUpdateOne {
	if value != "" {
		return d.SetRemark(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdate) SetNotEmptyParentID(value uint64) *DepartmentUpdate {
	if value != 0 {
		return d.SetParentID(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DepartmentUpdateOne) SetNotEmptyParentID(value uint64) *DepartmentUpdateOne {
	if value != 0 {
		return d.SetParentID(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyCreatedBy(value string) *DictionaryUpdate {
	if value != "" {
		return d.SetCreatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyCreatedBy(value string) *DictionaryUpdateOne {
	if value != "" {
		return d.SetCreatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyUpdatedBy(value string) *DictionaryUpdate {
	if value != "" {
		return d.SetUpdatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyUpdatedBy(value string) *DictionaryUpdateOne {
	if value != "" {
		return d.SetUpdatedBy(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyStatus(value uint8) *DictionaryUpdate {
	if value != 0 {
		return d.SetStatus(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyStatus(value uint8) *DictionaryUpdateOne {
	if value != 0 {
		return d.SetStatus(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyTitle(value string) *DictionaryUpdate {
	if value != "" {
		return d.SetTitle(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyTitle(value string) *DictionaryUpdateOne {
	if value != "" {
		return d.SetTitle(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyName(value string) *DictionaryUpdate {
	if value != "" {
		return d.SetName(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyName(value string) *DictionaryUpdateOne {
	if value != "" {
		return d.SetName(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdate) SetNotEmptyDesc(value string) *DictionaryUpdate {
	if value != "" {
		return d.SetDesc(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (d *DictionaryUpdateOne) SetNotEmptyDesc(value string) *DictionaryUpdateOne {
	if value != "" {
		return d.SetDesc(value)
	}
	return d
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyCreatedBy(value string) *DictionaryDetailUpdate {
	if value != "" {
		return dd.SetCreatedBy(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyCreatedBy(value string) *DictionaryDetailUpdateOne {
	if value != "" {
		return dd.SetCreatedBy(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyUpdatedBy(value string) *DictionaryDetailUpdate {
	if value != "" {
		return dd.SetUpdatedBy(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyUpdatedBy(value string) *DictionaryDetailUpdateOne {
	if value != "" {
		return dd.SetUpdatedBy(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyStatus(value uint8) *DictionaryDetailUpdate {
	if value != 0 {
		return dd.SetStatus(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyStatus(value uint8) *DictionaryDetailUpdateOne {
	if value != 0 {
		return dd.SetStatus(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptySort(value uint32) *DictionaryDetailUpdate {
	if value != 0 {
		return dd.SetSort(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptySort(value uint32) *DictionaryDetailUpdateOne {
	if value != 0 {
		return dd.SetSort(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyTitle(value string) *DictionaryDetailUpdate {
	if value != "" {
		return dd.SetTitle(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyTitle(value string) *DictionaryDetailUpdateOne {
	if value != "" {
		return dd.SetTitle(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyKey(value string) *DictionaryDetailUpdate {
	if value != "" {
		return dd.SetKey(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyKey(value string) *DictionaryDetailUpdateOne {
	if value != "" {
		return dd.SetKey(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyValue(value string) *DictionaryDetailUpdate {
	if value != "" {
		return dd.SetValue(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyValue(value string) *DictionaryDetailUpdateOne {
	if value != "" {
		return dd.SetValue(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdate) SetNotEmptyDictionaryID(value uint64) *DictionaryDetailUpdate {
	if value != 0 {
		return dd.SetDictionaryID(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (dd *DictionaryDetailUpdateOne) SetNotEmptyDictionaryID(value uint64) *DictionaryDetailUpdateOne {
	if value != 0 {
		return dd.SetDictionaryID(value)
	}
	return dd
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyCreatedBy(value string) *MenuUpdate {
	if value != "" {
		return m.SetCreatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyCreatedBy(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetCreatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyUpdatedBy(value string) *MenuUpdate {
	if value != "" {
		return m.SetUpdatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyUpdatedBy(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetUpdatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptySort(value uint32) *MenuUpdate {
	if value != 0 {
		return m.SetSort(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptySort(value uint32) *MenuUpdateOne {
	if value != 0 {
		return m.SetSort(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyParentID(value uint64) *MenuUpdate {
	if value != 0 {
		return m.SetParentID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyParentID(value uint64) *MenuUpdateOne {
	if value != 0 {
		return m.SetParentID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyMenuLevel(value uint32) *MenuUpdate {
	if value != 0 {
		return m.SetMenuLevel(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyMenuLevel(value uint32) *MenuUpdateOne {
	if value != 0 {
		return m.SetMenuLevel(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyMenuType(value uint32) *MenuUpdate {
	if value != 0 {
		return m.SetMenuType(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyMenuType(value uint32) *MenuUpdateOne {
	if value != 0 {
		return m.SetMenuType(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyPath(value string) *MenuUpdate {
	if value != "" {
		return m.SetPath(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyPath(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetPath(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyName(value string) *MenuUpdate {
	if value != "" {
		return m.SetName(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyName(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetName(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyRedirect(value string) *MenuUpdate {
	if value != "" {
		return m.SetRedirect(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyRedirect(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetRedirect(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyComponent(value string) *MenuUpdate {
	if value != "" {
		return m.SetComponent(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyComponent(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetComponent(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyTitle(value string) *MenuUpdate {
	if value != "" {
		return m.SetTitle(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyTitle(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetTitle(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyIcon(value string) *MenuUpdate {
	if value != "" {
		return m.SetIcon(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyIcon(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetIcon(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyFrameSrc(value string) *MenuUpdate {
	if value != "" {
		return m.SetFrameSrc(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyFrameSrc(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetFrameSrc(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyDynamicLevel(value uint32) *MenuUpdate {
	if value != 0 {
		return m.SetDynamicLevel(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyDynamicLevel(value uint32) *MenuUpdateOne {
	if value != 0 {
		return m.SetDynamicLevel(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdate) SetNotEmptyRealPath(value string) *MenuUpdate {
	if value != "" {
		return m.SetRealPath(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MenuUpdateOne) SetNotEmptyRealPath(value string) *MenuUpdateOne {
	if value != "" {
		return m.SetRealPath(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyCreatedBy(value string) *MenuParamUpdate {
	if value != "" {
		return mp.SetCreatedBy(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyCreatedBy(value string) *MenuParamUpdateOne {
	if value != "" {
		return mp.SetCreatedBy(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyUpdatedBy(value string) *MenuParamUpdate {
	if value != "" {
		return mp.SetUpdatedBy(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyUpdatedBy(value string) *MenuParamUpdateOne {
	if value != "" {
		return mp.SetUpdatedBy(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyType(value string) *MenuParamUpdate {
	if value != "" {
		return mp.SetType(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyType(value string) *MenuParamUpdateOne {
	if value != "" {
		return mp.SetType(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyKey(value string) *MenuParamUpdate {
	if value != "" {
		return mp.SetKey(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyKey(value string) *MenuParamUpdateOne {
	if value != "" {
		return mp.SetKey(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyValue(value string) *MenuParamUpdate {
	if value != "" {
		return mp.SetValue(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyValue(value string) *MenuParamUpdateOne {
	if value != "" {
		return mp.SetValue(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdate) SetNotEmptyMenuID(value uint64) *MenuParamUpdate {
	if value != 0 {
		return mp.SetMenuID(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (mp *MenuParamUpdateOne) SetNotEmptyMenuID(value uint64) *MenuParamUpdateOne {
	if value != 0 {
		return mp.SetMenuID(value)
	}
	return mp
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyCreatedBy(value string) *MerchantUpdate {
	if value != "" {
		return m.SetCreatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyCreatedBy(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetCreatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyUpdatedBy(value string) *MerchantUpdate {
	if value != "" {
		return m.SetUpdatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyUpdatedBy(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetUpdatedBy(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyStatus(value uint8) *MerchantUpdate {
	if value != 0 {
		return m.SetStatus(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyStatus(value uint8) *MerchantUpdateOne {
	if value != 0 {
		return m.SetStatus(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptySort(value uint32) *MerchantUpdate {
	if value != 0 {
		return m.SetSort(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptySort(value uint32) *MerchantUpdateOne {
	if value != 0 {
		return m.SetSort(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyName(value string) *MerchantUpdate {
	if value != "" {
		return m.SetName(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyName(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetName(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyLeader(value string) *MerchantUpdate {
	if value != "" {
		return m.SetLeader(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyLeader(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetLeader(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyPhone(value string) *MerchantUpdate {
	if value != "" {
		return m.SetPhone(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyPhone(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetPhone(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyEmail(value string) *MerchantUpdate {
	if value != "" {
		return m.SetEmail(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyEmail(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetEmail(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyRemark(value string) *MerchantUpdate {
	if value != "" {
		return m.SetRemark(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyRemark(value string) *MerchantUpdateOne {
	if value != "" {
		return m.SetRemark(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdate) SetNotEmptyParentID(value uint64) *MerchantUpdate {
	if value != 0 {
		return m.SetParentID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (m *MerchantUpdateOne) SetNotEmptyParentID(value uint64) *MerchantUpdateOne {
	if value != 0 {
		return m.SetParentID(value)
	}
	return m
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyCreatedBy(value string) *MerchantMetaUpdate {
	if value != "" {
		return mm.SetCreatedBy(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyCreatedBy(value string) *MerchantMetaUpdateOne {
	if value != "" {
		return mm.SetCreatedBy(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyUpdatedBy(value string) *MerchantMetaUpdate {
	if value != "" {
		return mm.SetUpdatedBy(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyUpdatedBy(value string) *MerchantMetaUpdateOne {
	if value != "" {
		return mm.SetUpdatedBy(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyStatus(value uint8) *MerchantMetaUpdate {
	if value != 0 {
		return mm.SetStatus(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyStatus(value uint8) *MerchantMetaUpdateOne {
	if value != 0 {
		return mm.SetStatus(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptySort(value uint32) *MerchantMetaUpdate {
	if value != 0 {
		return mm.SetSort(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptySort(value uint32) *MerchantMetaUpdateOne {
	if value != 0 {
		return mm.SetSort(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyTitle(value string) *MerchantMetaUpdate {
	if value != "" {
		return mm.SetTitle(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyTitle(value string) *MerchantMetaUpdateOne {
	if value != "" {
		return mm.SetTitle(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyKey(value string) *MerchantMetaUpdate {
	if value != "" {
		return mm.SetKey(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyKey(value string) *MerchantMetaUpdateOne {
	if value != "" {
		return mm.SetKey(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyValue(value string) *MerchantMetaUpdate {
	if value != "" {
		return mm.SetValue(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyValue(value string) *MerchantMetaUpdateOne {
	if value != "" {
		return mm.SetValue(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdate) SetNotEmptyMerchantID(value uint64) *MerchantMetaUpdate {
	if value != 0 {
		return mm.SetMerchantID(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (mm *MerchantMetaUpdateOne) SetNotEmptyMerchantID(value uint64) *MerchantMetaUpdateOne {
	if value != 0 {
		return mm.SetMerchantID(value)
	}
	return mm
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyCreatedBy(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetCreatedBy(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyCreatedBy(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetCreatedBy(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyUpdatedBy(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetUpdatedBy(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyUpdatedBy(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetUpdatedBy(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyName(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetName(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyName(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetName(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyClientID(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetClientID(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyClientID(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetClientID(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyClientSecret(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetClientSecret(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyClientSecret(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetClientSecret(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyRedirectURL(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetRedirectURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyRedirectURL(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetRedirectURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyScopes(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetScopes(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyScopes(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetScopes(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyAuthURL(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetAuthURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyAuthURL(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetAuthURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyTokenURL(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetTokenURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyTokenURL(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetTokenURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyAuthStyle(value uint64) *OauthProviderUpdate {
	if value != 0 {
		return op.SetAuthStyle(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyAuthStyle(value uint64) *OauthProviderUpdateOne {
	if value != 0 {
		return op.SetAuthStyle(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdate) SetNotEmptyInfoURL(value string) *OauthProviderUpdate {
	if value != "" {
		return op.SetInfoURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (op *OauthProviderUpdateOne) SetNotEmptyInfoURL(value string) *OauthProviderUpdateOne {
	if value != "" {
		return op.SetInfoURL(value)
	}
	return op
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyCreatedBy(value string) *PositionUpdate {
	if value != "" {
		return po.SetCreatedBy(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyCreatedBy(value string) *PositionUpdateOne {
	if value != "" {
		return po.SetCreatedBy(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyUpdatedBy(value string) *PositionUpdate {
	if value != "" {
		return po.SetUpdatedBy(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyUpdatedBy(value string) *PositionUpdateOne {
	if value != "" {
		return po.SetUpdatedBy(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyStatus(value uint8) *PositionUpdate {
	if value != 0 {
		return po.SetStatus(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyStatus(value uint8) *PositionUpdateOne {
	if value != 0 {
		return po.SetStatus(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptySort(value uint32) *PositionUpdate {
	if value != 0 {
		return po.SetSort(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptySort(value uint32) *PositionUpdateOne {
	if value != 0 {
		return po.SetSort(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyName(value string) *PositionUpdate {
	if value != "" {
		return po.SetName(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyName(value string) *PositionUpdateOne {
	if value != "" {
		return po.SetName(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyCode(value string) *PositionUpdate {
	if value != "" {
		return po.SetCode(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyCode(value string) *PositionUpdateOne {
	if value != "" {
		return po.SetCode(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdate) SetNotEmptyRemark(value string) *PositionUpdate {
	if value != "" {
		return po.SetRemark(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (po *PositionUpdateOne) SetNotEmptyRemark(value string) *PositionUpdateOne {
	if value != "" {
		return po.SetRemark(value)
	}
	return po
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyCreatedBy(value string) *RoleUpdate {
	if value != "" {
		return r.SetCreatedBy(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyCreatedBy(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetCreatedBy(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyUpdatedBy(value string) *RoleUpdate {
	if value != "" {
		return r.SetUpdatedBy(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyUpdatedBy(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetUpdatedBy(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyStatus(value uint8) *RoleUpdate {
	if value != 0 {
		return r.SetStatus(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyStatus(value uint8) *RoleUpdateOne {
	if value != 0 {
		return r.SetStatus(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyName(value string) *RoleUpdate {
	if value != "" {
		return r.SetName(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyName(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetName(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyCode(value string) *RoleUpdate {
	if value != "" {
		return r.SetCode(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyCode(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetCode(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyDefaultRouter(value string) *RoleUpdate {
	if value != "" {
		return r.SetDefaultRouter(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyDefaultRouter(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetDefaultRouter(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptyRemark(value string) *RoleUpdate {
	if value != "" {
		return r.SetRemark(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptyRemark(value string) *RoleUpdateOne {
	if value != "" {
		return r.SetRemark(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdate) SetNotEmptySort(value uint32) *RoleUpdate {
	if value != 0 {
		return r.SetSort(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (r *RoleUpdateOne) SetNotEmptySort(value uint32) *RoleUpdateOne {
	if value != 0 {
		return r.SetSort(value)
	}
	return r
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdate) SetNotEmptyStatus(value uint8) *TokenUpdate {
	if value != 0 {
		return t.SetStatus(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdateOne) SetNotEmptyStatus(value uint8) *TokenUpdateOne {
	if value != 0 {
		return t.SetStatus(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdate) SetNotEmptyToken(value string) *TokenUpdate {
	if value != "" {
		return t.SetToken(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdateOne) SetNotEmptyToken(value string) *TokenUpdateOne {
	if value != "" {
		return t.SetToken(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdate) SetNotEmptySource(value string) *TokenUpdate {
	if value != "" {
		return t.SetSource(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TokenUpdateOne) SetNotEmptySource(value string) *TokenUpdateOne {
	if value != "" {
		return t.SetSource(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyStatus(value uint8) *UserUpdate {
	if value != 0 {
		return u.SetStatus(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyStatus(value uint8) *UserUpdateOne {
	if value != 0 {
		return u.SetStatus(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyUsername(value string) *UserUpdate {
	if value != "" {
		return u.SetUsername(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyUsername(value string) *UserUpdateOne {
	if value != "" {
		return u.SetUsername(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyPassword(value string) *UserUpdate {
	if value != "" {
		return u.SetPassword(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyPassword(value string) *UserUpdateOne {
	if value != "" {
		return u.SetPassword(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyNickname(value string) *UserUpdate {
	if value != "" {
		return u.SetNickname(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyNickname(value string) *UserUpdateOne {
	if value != "" {
		return u.SetNickname(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyDescription(value string) *UserUpdate {
	if value != "" {
		return u.SetDescription(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyDescription(value string) *UserUpdateOne {
	if value != "" {
		return u.SetDescription(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyHomePath(value string) *UserUpdate {
	if value != "" {
		return u.SetHomePath(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyHomePath(value string) *UserUpdateOne {
	if value != "" {
		return u.SetHomePath(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyMobile(value string) *UserUpdate {
	if value != "" {
		return u.SetMobile(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyMobile(value string) *UserUpdateOne {
	if value != "" {
		return u.SetMobile(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyEmail(value string) *UserUpdate {
	if value != "" {
		return u.SetEmail(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyEmail(value string) *UserUpdateOne {
	if value != "" {
		return u.SetEmail(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyAvatar(value string) *UserUpdate {
	if value != "" {
		return u.SetAvatar(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyAvatar(value string) *UserUpdateOne {
	if value != "" {
		return u.SetAvatar(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyDepartmentID(value uint64) *UserUpdate {
	if value != 0 {
		return u.SetDepartmentID(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyDepartmentID(value uint64) *UserUpdateOne {
	if value != 0 {
		return u.SetDepartmentID(value)
	}
	return u
}
