// Code generated by ent, DO NOT EDIT.

package audit

import (
	"time"
)

const (
	// Label holds the string label denoting the audit type in the database.
	Label = "audit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldObjectName holds the string denoting the object_name field in the database.
	FieldObjectName = "object_name"
	// FieldActionName holds the string denoting the action_name field in the database.
	FieldActionName = "action_name"
	// FieldChangedData holds the string denoting the changed_data field in the database.
	FieldChangedData = "changed_data"
	// Table holds the table name of the audit in the database.
	Table = "sys_audits"
)

// Columns holds all SQL columns for audit fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldObjectName,
	FieldActionName,
	FieldChangedData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
